[package]
name = "chromatui-pty"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chromatui-core = { path = "../chromatui-core" }
portable-pty.workspace = true
