[package]
name = "chromatui-declarative"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chromatui-style = { path = "../chromatui-style" }
chromatui-layout = { path = "../chromatui-layout" }
