[package]
name = "chromatui-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
chromatui-algorithms = { path = "../chromatui-algorithms" }
crossterm = { version = "0.29", features = ["events"] }
